#!/system/bin/sh

tune2fs -o journal_data_writeback /dev/block/mmcblk0p1
tune2fs -O ^has_journal /dev/block/mmcblk0p1
tune2fs -o journal_data_writeback /dev/block/mmcblk0p2
tune2fs -O ^has_journal /dev/block/mmcblk0p1
tune2fs -o journal_data_writeback /dev/block/mmcblk0p8
tune2fs -O ^has_journal /dev/block/mmcblk0p8
tune2fs -o journal_data_writeback /block/path/to/system
tune2fs -O ^has_journal /block/path/to/system
tune2fs -o journal_data_writeback /block/path/to/cache
tune2fs -O ^has_journal /block/path/to/cache
tune2fs -o journal_data_writeback /block/path/to/data
tune2fs -O ^has_journal /block/path/to/data

sysctl -p /etc/sysctl.conf

echo "0" > /sys/block/mmcblk0/queue/rotational
echo "1024" > /sys/block/mmcblk0/queue/optimal_io_size
echo "64" > /sys/block/mmcblk0/queue/read_ahead_kb
echo "0" > /sys/block/mmcblk0/queue/iostats
echo "1" > /sys/block/mmcblk0/queue/iosched/group_isolation
echo "4" > /sys/block/mmcblk0/queue/iosched/quantum
echo "1" > /sys/block/mmcblk0/queue/iosched/low_latency
echo "5" > /sys/block/mmcblk0/queue/iosched/slice_idle
echo "1" > /sys/block/mmcblk0/queue/iosched/back_seek_penalty
echo "1000000000" > /sys/block/mmcblk0/queue/iosched/back_seek_max
echo "128" > /sys/block/mmcblk0/queue/nr_requests

echo "0" > /sys/block/mmcblk1/queue/rotational
echo "1024" > /sys/block/mmcblk1/queue/optimal_io_size
echo "64" > /sys/block/mmcblk1/queue/read_ahead_kb
echo "0" > /sys/block/mmcblk1/queue/iostats
echo "1" > /sys/block/mmcblk1/queue/iosched/group_isolation
echo "4" > /sys/block/mmcblk1/queue/iosched/quantum
echo "1" > /sys/block/mmcblk1/queue/iosched/low_latency
echo "5" > /sys/block/mmcblk1/queue/iosched/slice_idle
echo "1" > /sys/block/mmcblk1/queue/iosched/back_seek_penalty
echo "1000000000" > /sys/block/mmcblk1/queue/iosched/back_seek_max
echo "128" > /sys/block/mmcblk1/queue/nr_requests

busybox mount -o remount,noatime mmcblk0p1
busybox mount -o remount,noatime mmcblk0p2
busybox mount -o remount,noatime mmcblk0p8

busybox mount -o remount,commit=180 mmcblk0p1
busybox mount -o remount,commit=150 mmcblk0p2
busybox mount -o remount,commit=120 mmcblk0p8

busybox mount -o remount,noauto_da_alloc /system /system
busybox mount -o remount,noauto_da_alloc /data /data
busybox mount -o remount,noauto_da_alloc /cache /cache

