#!/system/bin/sh  

#
# build.prop
#
setprop ro.sf.lcd_density 240;
setprop wifi.supplicant_scan_interval 600;
setprop windowsmgr.max_events_per_sec 150;
setprop ro.telephony.call.ring.delay 400;
setprop dalvik.vm.heapsize 48m;
setprop ro.lg.proximity.delay 25;
setprop persist.sys.use_dithering 0;
setprop persist.sys.purgeable_assets 1;
