#!/system/bin/sh

sysctl -p /etc/sysctl.conf;

LOOP=`ls -d /sys/block/loop*`;
blk0=`ls -d /sys/block/mmcblk0`;
blk1=`ls -d /sys/block/mmcblk1`;
MMC=`ls -d /sys/block/mmc*`;

for j in $MMC; do
	echo "0" > $j/queue/rotational;
	echo "4096" > $j/queue/read_ahead_kb;
	echo "0" > $j/queue/iostats;
	echo "1" > $j/queue/iosched/group_isolation;
	echo "4" > $j/queue/iosched/quantum;
	echo "1" > $j/queue/iosched/low_latency;
	echo "5" > $j/queue/iosched/slice_idle;
	echo "1" > $j/queue/iosched/back_seek_penalty;
	echo "1000000000" > $j/queue/iosched/back_seek_max;
done;

for k in $(busybox mount | grep relatime | cut -d " " -f3) ; do
sync;
busybox mount -o remount,noatime $k;
done;

busybox mount -o remount,noauto_da_alloc /system /system
busybox mount -o remount,noauto_da_alloc /data /data
busybox mount -o remount,noauto_da_alloc /cache /cache

for k in $(busybox mount | grep ext4 | cut -d " " -f3) ; do
sync;
busybox mount -o remount,commit=15 $k
done;

for i in /sys/block/*/queue/scheduler ; do
echo "bfq" > $i;
done;

if [ ! -f /sys/block/mmcblk0/queue/read_ahead_kb]
then
sleep 60
fi
echo "2048" > /sys/block/mmcblk0/queue/read_ahead_kb
if [ ! -f /sys/block/mmcblk1/queue/read_ahead_kb]
then
sleep 60
fi
echo "2048" > /sys/block/mmcblk1/queue/read_ahead_kb
if [ ! -f /sys/devices/virtual/bdi/179:0/read_ahead_kb]
then
sleep 60
fi
echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb

for a in $blk0 $blk1 $MMC ; do
	echo "512" > $a/queue/nr_requests;
done;

