#!/system/bin/sh  

#
# build.prop
#
setprop wifi.supplicant_scan_interval 600;
setprop windowsmgr.max_events_per_sec 60;
setprop ro.telephony.call.ring.delay 400;
setprop dalvik.vm.heapsize 48m;
setprop dalvik.vm.startheapsize 48m;
setprop ro.lg.proximity.delay 25;
setprop persist.sys.use_dithering 0;
setprop persist.sys.purgeable_assets 1;
# MinFree and VM parameters;
echo "1" > /proc/sys/vm/oom_kill_allocating_task;
echo "0,1,2,4,6,15" > /sys/module/lowmemorykiller/parameters/adj;
echo "2560,4096,6144,7680,8704,10240" > /sys/module/lowmemorykiller/parameters/minfree;
echo "0" > /proc/sys/vm/swappiness;
echo "3000" > /proc/sys/vm/dirty_expire_centisecs;
echo "500" > /proc/sys/vm/dirty_writeback_centisecs;
echo "3" > /proc/sys/vm/dirty_background_ratio;
echo "15" > /proc/sys/vm/dirty_ratio;
echo "70" > /proc/sys/vm/vfs_cache_pressure;
echo "4096" > /proc/sys/vm/min_free_kbytes;
# CPU scheduler;
echo "1000000" > /proc/sys/kernel/sched_latency_ns;
echo "25000" > /proc/sys/kernel/sched_wakeup_granularity_ns;
echo "100000" > /proc/sys/kernel/sched_min_granularity_ns;
echo "-1" > /proc/sys/kernel/sched_rt_runtime_us; 
echo "100000" > /proc/sys/kernel/sched_rt_period_us;
echo "95000" > /proc/sys/kernel/sched_rt_runtime_us;
}

