#!/system/bin/sh  

# MinFree and VM parameters;
echo "1" > /proc/sys/vm/oom_kill_allocating_task;
echo "0,1,2,4,6,15" > /sys/module/lowmemorykiller/parameters/adj;
echo "2560,4096,6144,7680,8704,10240" > /sys/module/lowmemorykiller/parameters/minfree;
echo "8" > /proc/sys/vm/swappiness;
# CPU;
chmod 666 /sys/devices/system/cpu/cpu1/online
echo 1 > /sys/devices/system/cpu/cpu1/online
chmod 444 /sys/devices/system/cpu/cpu1/online
# Failsafe remount opt;
busybox mount -o remount,noauto_da_alloc /system /system
busybox mount -o remount,noauto_da_alloc /data /data
busybox mount -o remount,noauto_da_alloc /cache /cache
